### ISSUE TITLE
og:imageを設定

### ISSUE THREAD

**Issue by kotaroooo0** [Yuto-Nakano/shuffle#10]

**Comment by yuto343** [comment]
og:image設定しました。（PR作ればよかった（次からします））
・ブログ以外のページ
![image](https://user-images.githubusercontent.com/43196286/82214163-5b838200-9950-11ea-8f18-5640c6465fe3.png)
・ブログページかつサムネイルがあった場合
![image](https://user-images.githubusercontent.com/43196286/82214326-9e455a00-9950-11ea-921b-684a1602ad55.png)

**Comment by kotaroooo0** [comment]
GOODすぎる
