### ISSUE TITLE
チェックがうまく表示されていないバグ?

### ISSUE THREAD

**Issue by kotaroooo0** [Yuto-Nakano/shuffle#6]
![image](https://user-images.githubusercontent.com/31947384/81698981-b5440200-94a1-11ea-9e7d-220625e51ec1.png)

**Comment by yuto343** [comment]
どういうことですかこれ(笑)

**Comment by kotaroooo0** [comment]
これ `check` じゃなくて✔︎みたいなんか入っているのが正常かと思ってたんだけどこれが正常なのかな。俺は文字がかぶってるし気になった。

**Comment by yuto343** [comment]
MicroCMSは僕が作ってないのでどうしようもないですwww
ここ僕には普通にチェックマークで見えてました。
