### ISSUE TITLE
記事作成時にtweetしたい

### ISSUE THREAD

**Issue by yuto343** [Yuto-Nakano/shuffle#7]

**Comment by kotaroooo0** [comment]
実現方法
1. MicroCMSからNetlifyにhookしたときに、TwitterAPIを投げる
      - 既存のhookを使えるため、実装が用意
      - Netlifyの設定はGUI上にしかない?
2. MicroCMSからGithubActionsにhookするようにし、TwitterAPIを投げる
      - GithubActionsを導入するのが時間がかかるかもしれない
      - ついでにCI機能もつけられる

**Comment by kotaroooo0** [comment]
webhookで記事を新規追加したときに、記事の内容やタイトルも送られてくると勘違いしていたが、そもそもそんなことはないらしい。から、上のやり方だけじゃできない。

**Comment by kotaroooo0** [comment]
webhookで通知して、netlify / GithubActions上で記事内容を集めて、TwitterAPIを投げる
もしくは、自分でwebhookを受けるサーバーを立てて処理する。

追記: どうやらNetlify無料プランではプロジェクトをシェアできないので茨の道を進むしかない。

**Comment by kotaroooo0** [comment]
microCMSで記事を投稿してから反映するまで3分程度かかる。
`curl "https://shuffle-snow.microcms.io/api/v1/blogs" -H "X-API-KEY: hoge"` で
```
{"contents":[{"id":"uuccd88q4","createdAt":"2020-05-18T11:43:07.610Z","updatedAt":"2020-05-18T11:43:18.143Z","title":"test","sentence":"<p>test</p>"},{hoge},{fuga}
```
みたいなものが取れる。

1. hook用の簡単なサーバーを立てて新規ブログ記事をwebhookする。
2. 3分後くらいにブログ記事一覧APIを投げてブログ記事を取得する。
3. 最新の記事について @shuffle_DUでツイートする。

**Comment by kotaroooo0** [comment]
docker + heroku
https://devcenter.heroku.com/categories/deploying-with-docker

herokuは複数人から同時に触れるようなプラグインがあるらしい
https://qiita.com/kamillle/items/687f8fc0634aef1c11f0

**Comment by yuto343** [comment]
スゴイ...茨の道だったとはw
今更ですがデプロイherokuに変えましょか？

**Comment by kotaroooo0** [comment]
この機能がherokuでもできていい感じだった場合、一つにまとめることも検討しよう

**Comment by kotaroooo0** [comment]
TODO
- [ ] ~docker上でgoを動かす~
- [x] herokuにあげる
- [x] custom webhook設定する
- [ ] クソコードが散見されるので余裕があったら落穂拾いする
- [x] READMEを編集
- [x] Makefileをつくる

**Comment by yuto343** [comment]
今更ですが、@kotaroooo0さんが新しいレポジトリ作ってそこに今あるこのリポジトリのmasterを常にpushするようにしておいて(circleCI)、その光太郎さんのレポジトリをnetlifyにデプロイしたらnetlify functionを使ってできるな。と思いました。もし今の方法でツラくなったら考えてみてください！

**Comment by kotaroooo0** [comment]
なにいってるかわからんからあとで教えて

**Comment by kotaroooo0** [comment]
`git subtree push --prefix webhook_server/ heroku master`

**Comment by kotaroooo0** [comment]
できた
![image](https://user-images.githubusercontent.com/31947384/83346602-dd17de80-a358-11ea-99c8-6941c32a2e38.png)

**Comment by yuto343** [comment]
感動しました。ありがとうございます！

**Comment by yuto343** [comment]
閉じます〜
