### ISSUE TITLE
記事プレビューが見たい

### ISSUE THREAD

**Issue by kotaroooo0** [Yuto-Nakano/shuffle#9]
![image](https://user-images.githubusercontent.com/31947384/82122176-f6ebea00-97cc-11ea-8f77-ebd431786db6.png)

**Comment by yuto343** [comment]
そんな機能があったのか

**Comment by yuto343** [comment]
記事ページをビルド時に生成しているので少し工夫が必要そう

**Comment by yuto343** [comment]
@kotaroooo0 記事プレビュー実装しました〜〜〜
リッチエディタで出力できるhtmlのマークアップにいい感じにcssが当たってない可能性があるのでそういうところを発見したらまた教えてください〜

**Comment by yuto343** [comment]
あとこの実装日本語の知見全くなかったのでqiitaの記事に書いたらバズりそう

**Comment by kotaroooo0** [comment]
APIKEYをベタがきしてるやつをgithubに載せるのは好ましくない

**Comment by kotaroooo0** [comment]
getのリクエストしかなかった気がするから死ぬことはないけど、今後かわるかもしれんし、そこらへんのcommit消して、環境変数から取得するようにするのが望ましい

**Comment by kotaroooo0** [comment]
具体的にいうと、APIKEYを知ってる人は誰でも下書きプレビューが見れてしまう(GET)ってことで、ただ勝手に投稿されたり(POST)はされない

**Comment by kotaroooo0** [comment]
POSTもあったわ

**Comment by kotaroooo0** [comment]
絶対けしたほうがええわ

**Comment by kotaroooo0** [comment]
下書きのcontent_idしらないと見えんし下書きが見られることも一応ないのか
